# /CGA-Arco-Consultoria/frontend/Dockerfile.dev

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# O Vite precisa ser exposto na rede do container para o Docker Compose acessar
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]